### ISSUE TITLE
Rimsenal

### ISSUE THREAD

**Issue by pirate1337** [AthenaSulisMinerva/CombatExtendedFastTrack#289] opened 2020-02-08 02:53 UTC
NOTE: This is for requesting patches for a *new* third-party mod that CE:FT hasn't supported yet; if you are requesting changes to patches for an *existing* mod, please submit a Bug Report instead.

## Basic Information
Rimsenal
Gun pack

**Ludeon Forums forum topic:**

N/A

**GitHub repo homepage:**

N/A

**Steam Workshop page:**

https://steamcommunity.com/sharedfiles/filedetails/?id=725947920

## Detailed Information

- Ammunition (e.g. Shells)
- Apparel, Armor (e.g. Helmets, Vests)
- Apparel, General (e.g. Clothes, Hats, Gasmasks)
- Apparel, Loadbearing (e.g. Backpacks, Harnesses)
- Weapons, Ranged (e.g. Pistols, Rifles, Rocket Launchers)

**Are there existing CE versions of the mod or patches out there?:**
https://steamcommunity.com/sharedfiles/filedetails/?id=725947920

**Comment by AthenaSulisMinerva** [comment] 2020-02-08 07:57
Duplicate of #55

@pirate1337, please search the issue tracker more thoroughly in the future, and make sure you're not requesting something that is already requested.

**Closed** 2020-02-08 07:58 UTC
Labels: duplicate, mod compatiblity patch
