### ISSUE TITLE
rimworld of magic technomancer engingeer weapon

### ISSUE THREAD

**Issue by picard65** [AthenaSulisMinerva/CombatExtendedFastTrack#53] opened 2019-09-24 16:43 UTC
when you try to copy a weapon with the technomancer power it does not create any of them (tryed with more mods and with only core, fasttrack combat extended, rimworld of magic, and hugslib and jecstools, as those last two are prerequisites of rimworld of magic) this is what the log has to say about that:

cannot copy target thing or unable to restore techno weapon
Verse.Log:Message(String, Boolean)
TorannMagic.TM_Action:DoAction_TechnoWeaponCopy(Pawn, Thing)
TorannMagic.Verb_TechnoWeapon:TryCastShot()
Verse.Verb:TryCastNextBurstShot_Patch1(Object)
AbilityUser.Verb_UseAbility:WarmupComplete()
Verse.Stance_Warmup:Expire()
Verse.Stance_Busy:StanceTick()
Verse.Stance_Warmup:StanceTick()
Verse.Pawn_StanceTracker:StanceTrackerTick()
Verse.Pawn:Tick_Patch1(Object)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by sumghai** [comment] 2019-09-26 11:08
@AthenaSulisMinerva - You should test this out on your end.

**Comment by AthenaSulisMinerva** [comment] 2019-09-26 11:34
Sure thing.

**Comment by AthenaSulisMinerva** [comment] 2020-01-08 00:06
There is a newer duplicate of this issue, but since the latter complies with our issue reporting guidelines, has more complete information and mentions RoM's mod author itself, I'll make an exception by closing this older issue instead.

**Closed** 2020-01-08 00:06 UTC
Labels: third-party mod issue
