### ISSUE TITLE
LWM's Deep Storage broken as of latest CE:FT Update

### ISSUE THREAD

**Issue by nemisZZL** [AthenaSulisMinerva/CombatExtendedFastTrack#270] opened 2020-01-27 12:20 UTC
Windows 10 x64
Rimworld 1.0.2408
CE:FT Version: v1.0.1.8-FT-013

With the mod *LWM's Deep Storage*, you should be able to place several item stacks on a single tile on eg. on a storage shelf or a box.
However, having several item stacks on a single tile seems to be broken as of the *latest CE:FT* version.
Stacks of items now spill out from where they used to be stacked ontop of each other, breaking walls to make space for themselves.

This problem only started occuring after the *latest update*, and I've made no changes to my mod list.
I've done some testing, and removing CE:FT seems to fix the issue completely.

Here's my logs:
https://gist.github.com/HugsLibRecordKeeper/a0636ef521ad580c5cf642bf75550524#file-output_log-txt

Here's the mod in question:
https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896

EDIT:
I verified that this is a problem with the latest CE:FT version by downloading the previous version of CE:FT. Works just fine.

Thanks in advance!

**Comment by AthenaSulisMinerva** [comment] 2020-01-27 15:03
I am currently running CE:FT v1.0.1.8-FT-013 just fine with LWM Deep Storage 1.0.0.11, in both new and existing savegames.

Your log file mentions VFES, which CE:FT does not officially support, and the mod itself is also a WIP.

Does the issue disappear if you start a new savegame after removing VFES?

**Comment by nemisZZL** [comment] 2020-01-27 16:36
Yup, VFES + VFES CE Patch seems to be the issue. There's even comments on VFES CE Patch's steam page complaining about a range of bugs.

That being said, the problem only started occuring after the latest CE:FT update, before which everything was running fine.

In short, my issue is fixed by removing VFES and the VFES CE Patch, or alternatvely by using an older CE:FT version.

**Comment by AthenaSulisMinerva** [comment] 2020-01-28 06:14
Since the root cause is no longer Deep Storage, and we have existing issues elsewhere for VFES CE, I'm going to close this up.

**Closed** 2020-01-28 06:16 UTC
Labels: invalid/won't fix, third-party mod issue
