### ISSUE TITLE
No Mechanoid raids

### ISSUE THREAD

**Issue by Inazuma00** [AthenaSulisMinerva/CombatExtendedFastTrack#26] opened 2019-08-12 19:22 UTC
somehow the mod is preventing mechanoid raids to appear. i only have this mod loaded and tried to spawn a raid but only get an error and no raid appears.

**Comment by Taranchuk** [comment] 2019-08-13 12:11
Same problem. Although I’m not sure whether the problem is in this mod or in what else, but I’m at the 4 year of the colony and there were no mechanoid raids. Regular raids come normally. I do not know how to narrow down the number of potentially conflicting mods without a long wait for mechanoid raids in the game.

**Comment by AthenaSulisMinerva** [comment] 2019-08-16 13:26
This is unexpected.

CE:FT has made no changes to Mechanoid raid incidence, as it just adds compatibility patches. Are you sure this issue isn't also present in the original CE mod?

**Comment by Taranchuk** [comment] 2019-08-16 16:51
Well, I think the problem is in other mods (at least in my case)
When I leave these mods on:
```
    <li>Core</li>
    <li>HugsLib</li>
    <li>Combat Extended</li>
```
and spawn mechanoids raid. then they come normally. When I mechanoids with other mods, some kind of error occurs in the debug log and they do not appear on the map. Now it remains only to narrow down the  conflicting mods, but a lot of time needs to be spent on dropping out mods and testing.

**Comment by Inazuma00** [comment] 2019-08-17 07:06
ah it looks like its CE itself thats stopping the mechanoid raid, it spawned fine when i was using vanilla but was getting these error when i used CE

https://gist.github.com/HugsLibRecordKeeper/1116efc6d03d1d8730d94bff3260dd86 <- CE:FT
https://gist.github.com/HugsLibRecordKeeper/e13b113e24fae1f399586be1f2432ebb

**Comment by AthenaSulisMinerva** [comment] 2019-08-17 12:05
@Taranchuk, if you can also confirm @Inazuma00's observation that the problem is with the original CE mod itself, then I can mark this issue accordingly before closing.

You guys may also wish to notify @NoImageAvailable of the issue in his repo.

**Comment by Taranchuk** [comment] 2019-08-17 14:32
In my case, it’s definitely not about CE, they spawn perfectly when I use only this mod. But I still could not find out which mods are responsible for the lack of mechanoids, because I deleted one mode that was responsible for the spawn error, but without it the mechanoids still do not come and a lot of time has passed.

**Comment by AthenaSulisMinerva** [comment] 2019-08-18 00:51
At any rate, this isn't really our problem anymore.

**Closed by AthenaSulisMinerva** 2019-08-18 00:51 UTC
Labels: base CE mod issue, won't fix
