### ISSUE TITLE
Purple boxes when Rimmu-Nation is installed

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#127] opened 2019-11-09 08:40 UTC
As the title above states, after CE 1.6, it seems that when rimmunation is installed, all vanilla hats and even hats added in from VAE causes purple boxes on the pawns. My guess is the new layer system is conflicting with someone else Rimmu-Nation has added as once rimmu-nation is removed, the textures on pawns display as normal.
Rimmunation textures such as helmets and molle harness display normally in this regard, the purple boxes only appear when both rimmunation is installed and CE 1.6/CE FT

**Comment by Theblessedwant** [comment] 2019-11-09 08:48
This code seems to be causing the issue, 
![156a3577644af5484e39aeb801f433b0](https://user-images.githubusercontent.com/57470753/68525794-41694700-0310-11ea-9972-5f70a0a656a3.png)
![e396b0585a222fbe7f7653b226a4ba4b](https://user-images.githubusercontent.com/57470753/68525828-b2a8fa00-0310-11ea-8d4d-34c8fbf7ef8e.png)

**Comment by sumghai** [comment] 2019-11-09 08:58
Ooh, interesting detective work! So we've narrowed down the cause to at least one of the Rimmu-Nation mods.

Would removing that Python script file help mitigate the issue? Or would you still see pink squares?

**Comment by Theblessedwant** [comment] 2019-11-09 09:18
No it doesnt, it may be part of the harmony script
![83f9e0f4583214aa41560241b5a85125](https://user-images.githubusercontent.com/57470753/68526267-e8e87880-0314-11ea-84ab-3189df67f15f.png)

**Comment by Theblessedwant** [comment] 2019-11-09 09:18
Either that or there are other mods with that specific dll that is causing this issue

**Comment by Theblessedwant** [comment] 2019-11-09 09:26
I have narrowed down the issue to this specific dll
By removing it from all red horse mods, factions included ive managed to remove the issue caused rimmu-nation. Seeing as this is a dll issue, it would require chickenplucker to remove said dll or CE FT rewriting some part of the clothing layer system.
![8022d8e1f2e170df1acc74b9a40451de](https://user-images.githubusercontent.com/57470753/68526374-02d68b00-0316-11ea-9bfc-9643a63d0c98.png)

![4e05e8338be28ef35f620611c5ce8fee](https://user-images.githubusercontent.com/57470753/68526346-c0ad4980-0315-11ea-8489-b57a6cc5fc0f.png)

**Comment by sumghai** [comment] 2019-11-09 09:40
Right, this is because CE / CE:FT 1.6 includes new apparel layers - NiA had to also rewrite his own Don't Shave Your Head! mod to account for the same changes.

Since Chicken Plucker's forte isn't in coding, getting him to write a CE specific version of  the GraphicApparelDetour assembly is a bit too much for him (or whoever he's contracted to do the coding).

To be honest, I've never understood what exactly these mystery meat DLLs in the RH mods are used for. Any ideas?

**Comment by Theblessedwant** [comment] 2019-11-09 09:41
Removing said DLLs seem to have no effect on the mod what so ever, so my recommendation would be to just remove said dll, if you would like i can decompile said dll to see what is causing the issue. I suspect that both chickenplucker's DLL and CE 1.6's DLL are calling the same class which causes the weird texture issues.

**Comment by sumghai** [comment] 2019-11-09 10:00
That would be greatly appreciated!

I'll tag this issue with the `third-party mod issue` label for documentation purposes, but otherwise we'll keep it open until it is fully resolved.

**Comment by Hallanvaara** [comment] 2019-11-10 00:19
Can confirm. Removing this file from mods that add gear will remove purple boxes.

**Comment by Magichp** [comment] 2019-11-11 22:58
I removed that dll from my local modlist (the only one containing it was prisonner outfit, which I removed entirely) but I still encounter those purple squares everywhere. Any other possible culprit?

**Comment by sumghai** [comment] 2019-11-11 23:23
I believe there are other non-Rimmu Nation mods out there which may also be using this DLL.

If you are running Windows, browse to the RimWorld Mods folder in Explorer, and use the search bar to find all instances of this DLL. You can then delete them at your leisure.

**Comment by Magichp** [comment] 2019-11-12 00:11
That is exactly what I did ^^ And the only instance of the file was in Prisonner outfit, I removed the mod and unsuscribed from it but the issue is still present. There are no other GraphicApparelDetour.dll in my "Mods" folder (only using local copies of mods in order to debug).

**Comment by sumghai** [comment] 2019-11-12 03:35
In that case, you're going to have to conduct a binary search:

* Start by confirming that the purple box bug does not happen when you only have Core and CE:FT running
* Next, add half of all your other mods
* If the purple boxes do not appear, the problem is with the other half of your mod
* If the purple boxes **do** appear, then set aside half of your current set and test
* Repeat interactively until you have narrow down the culprit

**Comment by Theblessedwant** [comment] 2019-11-12 06:11
If there is a DLL there is rerouting layers, that would likely be the issue. The issue is probably an apparel mod you have, could you list the apparel mods you may have?

**Comment by Magichp** [comment] 2019-11-12 06:16
I have a few races mods that add apparels but I don't think I have any "apparel only" mods. Ill try to hunt down the issue and report back.

**Comment by Theblessedwant** [comment] 2019-11-14 04:20
Hi there CE FT team, ive attempted to decompile said dll and tried looking through the code. based on what i can gather, the main use of the code is to maintain a constant colour across certain clothing items. Based on the aforementioned errors, it seems that the dll is successfully injected which causes said error.  I suspect, since CE chaanges face rendering overhead etc, this line of code derps out as overhead is no longer a valid layer.
![021afe85960f9b88b98569d517ed244d](https://user-images.githubusercontent.com/57470753/68826507-31b77d00-06d9-11ea-8f18-4754a9dcaaf1.png)

**Comment by Theblessedwant** [comment] 2019-11-14 04:26
Im not a C# expert but what i think the code is doing is changing how the base overhead layer behaves. Since CE adds 3 different head layers now, any layer that doesnt utilize the overhead layer just derps out as this dll only recognizes one single headlayer.

**Comment by Theblessedwant** [comment] 2019-11-14 04:28
Im not sure if it will work but would it be possible to add the CE layers into this dll, it MAY cause issues that im not aware of.

**Comment by sumghai** [comment] 2019-11-14 04:34
I think that this is now primarily the responsibility of whoever originally wrote the GraphicApparelDetour assembly to update their code to be compatible with CE/CE:FT, so there really isn't much we can do.

@Theblessedwant, could you find out who is responsible for maintaining that assembly and direct them over to this ticket? Once we're sure they understand the context of the issue, we can close this and hand over the responsibility of fixing the bug to them.

**Comment by Theblessedwant** [comment] 2019-11-14 04:38
Ive tried to get in touch which chicken plucker but ive not had any luck so far

**Comment by Theblessedwant** [comment] 2019-11-14 05:45
Unfortunately, after getting into contact with chicken plucker on discord, he has disclosed that he has no wish to edit his mods for the sake of CE, this goes beyond simple xml edits and into the C# code. Further he has stated that he doesnt want a reuploaded CE compatible version on steam and i will respect that. So unfortunately, rimmu-nation will remain incompatible for the forseeable future

**Comment by sumghai** [comment] 2019-11-14 08:37
Reopening temporarily for a response.

My understanding is that Chicken Plucker himself did not write the assembly (given C# is outside his area of expertise), and that he instead outsourced the work to another modder.

One of the reasons CE:FT was established was to specifically support modders like Chicken Plucker, whose work cannot be patched by the upstream CE mod due to political reasons. @Freedom187 and I wrote the initial RN patches with the understanding that Chicken Plucker did not need to involve himself at all, other than opening issues whenever he releases a new spin-off mod.

I can discuss options privately with Chicken Plucker, but in the grand scheme of things he himself personally will not need to expend any effort in making his mod compatible with CE:FT.

We'll do what we can.

**Closed by sumghai** 2019-11-14 08:37 UTC
Labels: base CE mod issue, third-party mod issue
