### ISSUE TITLE
Support Request for Sparkling Worlds

### ISSUE THREAD

**Issue by Totherphoenix** [AthenaSulisMinerva/CombatExtendedFastTrack#211] opened 2019-12-17 22:21 UTC
I understand there is an outdated (1.4 or 1.5?) fan-made patch for Sparkling Worlds, however I would love if some official support from the CE:FT team was provided for the weapons the mod adds - as it stands, the enemy faction in Sparkling worlds spawns without compatible ammunition, making them a non-threat in the late-game. 

On top of this, I am sure there are armours and weapons not quite working properly with CE mechanics.

Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922

**Comment by AthenaSulisMinerva** [comment] 2019-12-18 11:22
Duplicate of #95 

@Totherphoenix, please follow the [issue reporting guidelines](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/issues/175) and make sure that your issue hasn't already been asked by someone else before posting.

**Closed** 2019-12-18 11:22 UTC
Labels: duplicate, mod compatiblity patch
